# ---------------- #
#   Main Configs   #
# ---------------- #
title: Your awesome QAQ
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# ---------------- #
#      Author      #
# ---------------- #
github_username:  oscar60310
author: Ivan Tsai
location: Taiwan
email: oscar60310@gmail.com
# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  - href: /
    label: 首頁
  - href: /categories/
    label: 分類
  - href: /about/
    label: 關於
# ---------------- #
#    Comments      #
# ---------------- #
comments_provider: disqus
disqus:
    username: oscar60310