# ---------------- #
#   Main Configs   #
# ---------------- #
title: Goofy's Blog
subtitle: Thoughts, stories and ideas.
description: >- # this means to ignore newlines until "baseurl:"
  Goofy's Blog, share thoughts, stories and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.cptsai.com" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
lsi: false
quiet: false
permalink: /:year/:month/:day/:title/
subscribe_rss: /feed.xml
# ---------------- #
#      Author      #
# ---------------- #
github_username:  oscar60310
author: Ivan Tsai
location: Taiwan
email: oscar60310@gmail.com
# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  - href: /
    label: 首頁
  - href: /categories/
    label: 分類
  - href: /about/
    label: 關於
# ---------------- #
#    Comments      #
# ---------------- #
comments_provider: disqus
disqus:
    username: cptsai
# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
  fulltext: true
  limit: 10
google:
  analytics_id: UA-105833854-1